services:
  linkcom:
    build: .  # 本地构建
    # image: 918178/linkcom:latest  # DockerHub
    image: ghcr.io/neo-403/linkcom:latest  # Ghcr.io
    container_name: linkcom  # 自定义容器名称
    restart: unless-stopped  # 非手动停止则总是重启
    ports:
      - "18080:8080"
    environment:
      - PORT=8080  # 服务器端口
      # - BASE_PATH=/linkcom  # 子路径(Nginx使用)
    # volumes:
    #   - ./certs:/app/certs:ro  # 挂载证书(需在 server.js 启用 TLS)